### ISSUE TITLE
Tor support

### ISSUE THREAD

**Issue by chrisc93** [BlueWallet/rn-electrum-client#1]
I briefly looked through the code and it looks like a Tor proxy would be used in this lib. Could it be as simple as adding https://github.com/JoshGlazebrook/socks or https://github.com/TooTallNate/node-socks-proxy-agent into client.js? Looks like the url and port would come from the BlueWallet app too.

**Comment by Overtorment** [comment]
maybe https://github.com/JoshGlazebrook/socks can be plugged relatively easy.
but user would need to setup TOR proxy in order to use it (on 9050), so this wouldn't be a one-click -to-enable-tor solution

**Comment by chrisc93** [comment]
Good point. I'm running android w/orbot so I was thinking of that scenario.

**Comment by chrisc93** [comment]
Addressed in https://github.com/BlueWallet/rn-electrum-client/pull/4
