### ISSUE TITLE
Error close connect with tls connection

### ISSUE THREAD

**Issue by mattiaferrari02** [BlueWallet/rn-electrum-client#11]
I tried connecting to `blockstream.info:465` using tls connection, I did the necessary polyfills of `net` and `tls` and I tried also with the method that you are using [here](https://github.com/BlueWallet/BlueWallet/blob/f331c632fbb7c8aaa07e4868f1141b03d6eb6826/blue_modules/tls.js)
It seems that I'm connected for a short time but then the connection closes and starts trying to reconnect, as the result I obtain a bunch of errors `Error: close connect`.
I tried the same thing with tcp on `blockstream.info:195` and it works properly, the problem is that i need to connect to this one `blockstream.info:465`using tls

![Screenshot 2022-12-01 at 17 22 34](https://user-images.githubusercontent.com/65465360/205105529-0295efda-b504-4646-b7ff-e826bf6fbbb8.png)

<img width="457" alt="Screenshot 2022-12-01 at 17 23 29" src="https://user-images.githubusercontent.com/65465360/205105712-3157e5c9-341d-4f4f-b905-989c93cc2662.png">

Am I missing something?

**Comment by Overtorment** [comment]
`blockstream.info:465` doesnt look like a valid electrum server at all.

heres an example testing valid electrum with tls:

```bash
$ echo '{"id": 1, "method": "blockchain.scripthash.get_balance", "params": ["716decbe1660861c3d93906cb1d98ee68b154fd4d23aed9783859c1271b52a9c"]}' | timeout 2 openssl s_client -quiet  -connect electrum1.bluewallet.io:443 2>/dev/null
{"jsonrpc":"2.0","result":{"confirmed":51432,"unconfirmed":0},"id":1}
```



the one you provided returns nothing and just closes the connection:


```bash
$ echo '{"id": 1, "method": "blockchain.scripthash.get_balance", "params": ["716decbe1660861c3d93906cb1d98ee68b154fd4d23aed9783859c1271b52a9c"]}' | timeout 2 openssl s_client -quiet  -connect blockstream.info:465 2>/dev/null
$ 
```

**Comment by Overtorment** [comment]
>> And also I tried with electrum1.bluewallet.io:443 and it doesn't work in the same way of blockstream:465.
>> It seems that the problem consists in the polyfill of tls or tcp himself

but this works in BlueWallet, no? whats the difference?
i peeped quickly, and I see socket dep is newer in your example, can you downgrade to the one BW uses? i remember there were some breaking changes, thats why its not up-to-date
